language: python
python:
  - "3.5"
  - "3.6"
install:
- pip install -r requirements.txt
- pip install sphinx numpydoc matplotlib python-coveralls sphinx-gallery scikit-image
- python setup.py develop
script:
- NUMBA_DISABLE_JIT=1 DISABLE_TQDM=1 py.test -v --cov=copt
after_success: coveralls
cache:
  directories:
    - $HOME/copt_data
